import CustomNavbar from '@/components/CustomNavbar'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/components/Footer'
//(1) install react-toastify
//(2) import these 2
{/*(3)put this <ToastContainer/> */}
import "react-toastify/dist/ReactToastify.css"
import { ToastContainer } from 'react-toastify'
import UserContext from '@/context/userContext'
import UserProvider from '@/context/userProvider'
import MyNavbar from '@/components/MyNvabar'

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <UserContext.Provider value={user}> */}
        <UserProvider>
        <ToastContainer autoClose= "3000"  draggablePercent={60}/>
        {/* <h1>This is main Header Layout</h1> */}
        {/* <CustomNavbar/> */}
        <MyNavbar/>
        {/* <div className='flex justify-around'> */}
          {/* <div><h1>Side Menu</h1></div> */}
          <div className='mt-0'>{children}</div>
        {/* </div> */}
       
        {/* <h1>This is main Footer Layout</h1> */}
        <Footer/>
        </UserProvider>
        {/* </UserContext.Provider> */}
      </body>
    </html>
  )
}
